# LOGGING
logging:
  level.root: INFO
  level.org.springframework: INFO
  level.com.ps.cre.reporting: INFO

batch-properties:
  chunkSize: 500
  nameJob: predictionJob

fichier-source:
  delimiter: ;
  path: src/resources/sources/tirages.csv

